spring.application.name=journal App
spring.data.mongodb.uri=mongodb+srv://nehaafreen003:yXGnFxjAcsREIB9Y@cluster0.olrvt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.username=
#spring.data.mongodb.password=
